import { Affiliation, Employee, Zone } from '@/types/types';

export const employees: Employee[] = [
  {
    id: '1',
    avatar: 'https://d2u8k2ocievbld.cloudfront.net/memojis/female/11.png',
    name: 'Tony Reichert',
    gender: 'Female',
    zone: Zone.CLevel,
    affiliation: Affiliation.Tech,
    age: '25-30',
    startYear: 2023,
  },
  {
    id: '2',
    avatar: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/11.png',
    name: 'Zoey Lang',
    zone: Zone.Backend,
    gender: 'Male',
    affiliation: Affiliation.PDFAid,
    age: '20-25',
    startYear: 2023,
  },
  {
    id: '3',
    avatar: 'https://d2u8k2ocievbld.cloudfront.net/memojis/female/9.png',
    name: 'Jane Fisher',
    zone: Zone.Backend,
    gender: 'Female',
    affiliation: Affiliation.Shared,
    age: '20-25',
    startYear: 2023,
  },
  {
    id: '4',
    avatar: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/11.png',
    name: 'William Howard',
    zone: Zone.Marketing,
    gender: 'Male',
    affiliation: Affiliation.Tech,
    age: '25-30',
    startYear: 2023,
  },
  {
    id: '5',
    avatar: 'https://d2u8k2ocievbld.cloudfront.net/memojis/female/12.png',
    name: 'Kristen Copper',
    zone: Zone.Growth,
    gender: 'Female',
    affiliation: Affiliation.BetterCV,
    age: '20-25',
    startYear: 2023,
  },
];
