import { Affiliation, Employee, Zone } from '@/types/types';

export const employees: Employee[] = [
  {
    id: '1',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/1-avatar.jpg',
    name: 'Dmytro Haranzha',
    gender: 'Male',
    zone: Zone.Growth,
    affiliation: Affiliation.Tech,
    age: '30+',
    startYear: 2021,
  },
  {
    id: '2',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/2-avatar.jpg',
    name: 'Ihor Shramko',
    zone: Zone.CLevel,
    gender: 'Male',
    affiliation: Affiliation.Shared,
    age: '30+',
    startYear: 2022,
  },
  {
    id: '3',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/3-avatar.jpg',
    name: 'Viacheslav Matskov',
    zone: Zone.CLevel,
    gender: 'Male',
    affiliation: Affiliation.Shared,
    age: '30+',
    startYear: 2021,
  },
  {
    id: '4',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/4-avatar.jpg',
    name: 'Kyrylo Tolokonnikov',
    zone: Zone.Growth,
    gender: 'Male',
    affiliation: Affiliation.PDFAid,
    age: '25-30',
    startYear: 2022,
  },
  {
    id: '5',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/5-avatar.jpg',
    name: 'Maksym Shatokhin',
    zone: Zone.Growth,
    gender: 'Male',
    affiliation: Affiliation.BetterCV,
    age: '20-25',
    startYear: 2024,
  },
  {
    id: '6',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/6-avatar.jpg',
    name: 'Mykola Bakhov',
    zone: Zone.Growth,
    gender: 'Male',
    affiliation: Affiliation.LegalForms,
    age: '25-30',
    startYear: 2022,
  },
  {
    id: '7',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/7-avatar.jpg',
    name: 'Oleksandr Gorbach',
    zone: Zone.Growth,
    gender: 'Male',
    affiliation: Affiliation.LegalAnswers,
    age: '25-30',
    startYear: 2024,
  },
  {
    id: '8',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/8-avatar.jpg',
    name: 'Oleksandra Hospod',
    zone: Zone.HR,
    gender: 'Female',
    affiliation: Affiliation.Shared,
    age: '30+',
    startYear: 2021,
  },
  {
    id: '9',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/9-avatar.jpg',
    name: 'Volodymyr Dontsov',
    zone: Zone.CLevel,
    gender: 'Male',
    affiliation: Affiliation.Shared,
    age: '30+',
    startYear: 2022,
  },
  {
    id: '10',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/10-avatar.jpg',
    name: 'Volodymyr Kupriienko',
    zone: Zone.Backend,
    gender: 'Male',
    affiliation: Affiliation.Shared,
    age: '25-30',
    startYear: 2022,
  },
  {
    id: '11',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/11-avatar.jpg',
    name: 'Yevhenii Honcharenko',
    zone: Zone.Frontend,
    gender: 'Male',
    affiliation: Affiliation.Shared,
    age: '30+',
    startYear: 2022,
  },
  {
    id: '12',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/12-avatar.jpg',
    name: 'Patrisiia Hevorkian',
    zone: Zone.HR,
    gender: 'Female',
    affiliation: Affiliation.Shared,
    age: '25-30',
    startYear: 2024,
  },
  {
    id: '13',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/13-avatar.jpg',
    name: 'Alina Matushchak',
    zone: Zone.Frontend,
    gender: 'Female',
    affiliation: Affiliation.LegalForms,
    age: '25-30',
    startYear: 2024,
  },
  {
    id: '14',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/14-avatar.jpg',
    name: 'Anastasiia Tilikina',
    zone: Zone.Frontend,
    gender: 'Female',
    affiliation: Affiliation.Tech,
    age: '25-30',
    startYear: 2023,
  },
  {
    id: '15',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/15-avatar.jpg',
    name: 'Nataliia Nagirna',
    zone: Zone.HR,
    gender: 'Female',
    affiliation: Affiliation.Shared,
    age: '25-30',
    startYear: 2022,
  },
  {
    id: '16',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/16-avatar.jpg',
    name: 'Anton Poroshkin',
    zone: Zone.Frontend,
    gender: 'Male',
    affiliation: Affiliation.LegalAnswers,
    age: '20-25',
    startYear: 2025,
  },
  {
    id: '17',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/17-avatar.jpg',
    name: 'Artem Tiutiunyk',
    zone: Zone.Frontend,
    gender: 'Male',
    affiliation: Affiliation.Tech,
    age: '20-25',
    startYear: 2024,
  },
  {
    id: '18',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/18-avatar.jpg',
    name: 'Nikita Panahoda',
    zone: Zone.Frontend,
    gender: 'Male',
    affiliation: Affiliation.Tech,
    age: '20-25',
    startYear: 2024,
  },
  {
    id: '19',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/19-avatar.jpg',
    name: 'Dmytro Pelovych',
    zone: Zone.Frontend,
    gender: 'Male',
    affiliation: Affiliation.Tech,
    age: '20-25',
    startYear: 2024,
  },
  {
    id: '20',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/20-avatar.jpg',
    name: 'Oleksandr Karakai',
    zone: Zone.Frontend,
    gender: 'Male',
    affiliation: Affiliation.BetterCV,
    age: '30+',
    startYear: 2022,
  },
  {
    id: '21',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/21-avatar.jpg',
    name: 'Oleksii Larchenko',
    zone: Zone.Frontend,
    gender: 'Male',
    affiliation: Affiliation.Tech,
    age: '20-25',
    startYear: 2024,
  },
  {
    id: '22',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/22-avatar.jpg',
    name: 'Pavlo Pshenyshnyi',
    zone: Zone.Frontend,
    gender: 'Male',
    affiliation: Affiliation.Shared,
    age: '20-25',
    startYear: 2024,
  },
  {
    id: '23',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/23-avatar.jpg',
    name: 'Vadym Akinshyn',
    zone: Zone.Frontend,
    gender: 'Male',
    affiliation: Affiliation.LegalAnswers,
    age: '25-30',
    startYear: 2024,
  },
  {
    id: '24',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/24-avatar.jpg',
    name: 'Yaroslav Illiashenko',
    zone: Zone.Frontend,
    gender: 'Male',
    affiliation: Affiliation.PDFAid,
    age: '25-30',
    startYear: 2023,
  },
  {
    id: '25',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/25-avatar.jpg',
    name: 'Ihor Petrov',
    zone: Zone.Frontend,
    gender: 'Male',
    affiliation: Affiliation.BetterCV,
    age: '20-25',
    startYear: 2025,
  },
  {
    id: '26',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/26-avatar.jpg',
    name: 'Ihor Honcharenko',
    zone: Zone.Frontend,
    gender: 'Male',
    affiliation: Affiliation.PDFAid,
    age: '20-25',
    startYear: 2024,
  },
  {
    id: '27',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/27-avatar.jpg',
    name: 'Oleksii Budnik',
    zone: Zone.Frontend,
    gender: 'Male',
    affiliation: Affiliation.PDFAid,
    age: '30+',
    startYear: 2024,
  },
  {
    id: '28',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/28-avatar.jpg',
    name: 'Pavlo Kodii',
    zone: Zone.Frontend,
    gender: 'Male',
    affiliation: Affiliation.PDFAid,
    age: '25-30',
    startYear: 2024,
  },
  {
    id: '29',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/29-avatar.jpg',
    name: 'Viktoriia Yakymenko',
    zone: Zone.Frontend,
    gender: 'Female',
    affiliation: Affiliation.PDFAid,
    age: '20-25',
    startYear: 2025,
  },
  {
    id: '30',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/30-avatar.jpg',
    name: 'Artem Filatov',
    zone: Zone.Operations,
    gender: 'Male',
    affiliation: Affiliation.Tech,
    age: '30+',
    startYear: 2022,
  },
  {
    id: '31',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/31-avatar.jpg',
    name: 'Kateryna Antypova',
    zone: Zone.Marketing,
    gender: 'Female',
    affiliation: Affiliation.Shared,
    age: '25-30',
    startYear: 2021,
  },
  {
    id: '32',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/32-avatar.jpg',
    name: 'Oleksandra Oliinyk',
    zone: Zone.DesignAndContent,
    gender: 'Female',
    affiliation: Affiliation.Shared,
    age: '25-30',
    startYear: 2022,
  },
  {
    id: '33',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/33-avatar.jpg',
    name: 'Rostyslav Rashchupkin',
    zone: Zone.Marketing,
    gender: 'Male',
    affiliation: Affiliation.PDFAid,
    age: '20-25',
    startYear: 2023,
  },
  {
    id: '34',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/34-avatar.jpg',
    name: 'Yana Koba',
    zone: Zone.DesignAndContent,
    gender: 'Female',
    affiliation: Affiliation.Shared,
    age: '30+',
    startYear: 2021,
  },
  {
    id: '35',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/35-avatar.jpg',
    name: 'Anastasiia Stadnik',
    zone: Zone.Operations,
    gender: 'Female',
    affiliation: Affiliation.Tech,
    age: '20-25',
    startYear: 2024,
  },
  {
    id: '36',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/36-avatar.jpg',
    name: 'Dmytro Syvyi',
    zone: Zone.Operations,
    gender: 'Male',
    affiliation: Affiliation.Tech,
    age: '30+',
    startYear: 2021,
  },
  {
    id: '37',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/37-avatar.jpg',
    name: 'Nataliia Vyshnevska',
    zone: Zone.Operations,
    gender: 'Female',
    affiliation: Affiliation.Shared,
    age: '30+',
    startYear: 2022,
  },
  {
    id: '38',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/38-avatar.jpg',
    name: 'Vladyslav Topchai',
    zone: Zone.Operations,
    gender: 'Male',
    affiliation: Affiliation.Tech,
    age: '25-30',
    startYear: 2021,
  },
  {
    id: '39',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/39-avatar.jpg',
    name: 'Anastasiia Lofytska',
    zone: Zone.DesignAndContent,
    gender: 'Female',
    affiliation: Affiliation.Shared,
    age: '20-25',
    startYear: 2025,
  },
  {
    id: '40',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/40-avatar.jpg',
    name: 'Viktor Shaituro',
    zone: Zone.Marketing,
    gender: 'Male',
    affiliation: Affiliation.BetterCV,
    age: '20-25',
    startYear: 2024,
  },
  {
    id: '41',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/41-avatar.jpg',
    name: 'Oleksii Sobko',
    zone: Zone.Marketing,
    gender: 'Male',
    affiliation: Affiliation.LegalAnswers,
    age: '20-25',
    startYear: 2024,
  },
  {
    id: '42',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/42-avatar.jpg',
    name: 'Oleksandr Kurylenko',
    zone: Zone.Marketing,
    gender: 'Male',
    affiliation: Affiliation.Tech,
    age: '25-30',
    startYear: 2022,
  },
  {
    id: '43',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/43-avatar.jpg',
    name: 'Kateryna Halstian',
    zone: Zone.Marketing,
    gender: 'Female',
    affiliation: Affiliation.Tech,
    age: '25-30',
    startYear: 2025,
  },
  {
    id: '44',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/44-avatar.jpg',
    name: 'Iryna Korinchak',
    zone: Zone.Marketing,
    gender: 'Female',
    affiliation: Affiliation.LegalForms,
    age: '30+',
    startYear: 2024,
  },
  {
    id: '45',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/45-avatar.jpg',
    name: 'Oleksandr Mazur',
    zone: Zone.Marketing,
    gender: 'Male',
    affiliation: Affiliation.PDFAid,
    age: '25-30',
    startYear: 2024,
  },
  {
    id: '46',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/46-avatar.jpg',
    name: 'Maksym Hordiienko',
    zone: Zone.DesignAndContent,
    gender: 'Male',
    affiliation: Affiliation.Tech,
    age: '25-30',
    startYear: 2024,
  },
  {
    id: '47',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/47-avatar.jpg',
    name: 'Oleksandra Svyda',
    zone: Zone.DesignAndContent,
    gender: 'Female',
    affiliation: Affiliation.PDFAid,
    age: '25-30',
    startYear: 2022,
  },
  {
    id: '48',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/48-avatar.jpg',
    name: 'Bohdan Hudzenko',
    zone: Zone.Product,
    gender: 'Male',
    affiliation: Affiliation.Shared,
    age: '25-30',
    startYear: 2021,
  },
  {
    id: '49',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/49-avatar.jpg',
    name: 'Yuliia Hordiienko',
    zone: Zone.Product,
    gender: 'Female',
    affiliation: Affiliation.Tech,
    age: '25-30',
    startYear: 2024,
  },
  {
    id: '50',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/50-avatar.jpg',
    name: 'Yuliia Lavrenko',
    zone: Zone.Product,
    gender: 'Female',
    affiliation: Affiliation.Tech,
    age: '25-30',
    startYear: 2025,
  },
  {
    id: '51',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/51-avatar.jpg',
    name: 'Oles Naida',
    zone: Zone.Product,
    gender: 'Male',
    affiliation: Affiliation.LegalAnswers,
    age: '20-25',
    startYear: 2025,
  },
  {
    id: '52',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/52-avatar.jpg',
    name: 'Vitalii Yovko',
    zone: Zone.Operations,
    gender: 'Male',
    affiliation: Affiliation.LegalAnswers,
    age: '25-30',
    startYear: 2022,
  },
  {
    id: '53',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/53-avatar.jpg',
    name: 'Serhii Zubov',
    zone: Zone.Backend,
    gender: 'Male',
    affiliation: Affiliation.Tech,
    age: '30+',
    startYear: 2024,
  },
  {
    id: '54',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/54-avatar.jpg',
    name: 'Oleksii Vasylenko',
    zone: Zone.Backend,
    gender: 'Male',
    affiliation: Affiliation.Shared,
    age: '25-30',
    startYear: 2024,
  },
  {
    id: '55',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/55-avatar.jpg',
    name: 'Oleksii Ilin',
    zone: Zone.Backend,
    gender: 'Male',
    affiliation: Affiliation.Shared,
    age: '25-30',
    startYear: 2024,
  },
  {
    id: '56',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/56-avatar.jpg',
    name: 'Maksym Chaika',
    zone: Zone.Backend,
    gender: 'Male',
    affiliation: Affiliation.Shared,
    age: '20-25',
    startYear: 2022,
  },
  {
    id: '57',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/57-avatar.jpg',
    name: 'Dariia Moisol',
    zone: Zone.Backend,
    gender: 'Female',
    affiliation: Affiliation.Shared,
    age: '20-25',
    startYear: 2022,
  },
  {
    id: '58',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/58-avatar.jpg',
    name: 'Artem Porubai',
    zone: Zone.Backend,
    gender: 'Male',
    affiliation: Affiliation.Shared,
    age: '30+',
    startYear: 2022,
  },
  {
    id: '59',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/59-avatar.jpg',
    name: 'Yevheniia Oshurko',
    zone: Zone.Analytics,
    gender: 'Female',
    affiliation: Affiliation.Shared,
    age: '25-30',
    startYear: 2024,
  },
  {
    id: '60',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/60-avatar.jpg',
    name: 'Vladyslav Orliuk',
    zone: Zone.Analytics,
    gender: 'Male',
    affiliation: Affiliation.Shared,
    age: '20-25',
    startYear: 2024,
  },
  {
    id: '61',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/61-avatar.jpg',
    name: 'Vitaliy Muzychuk',
    zone: Zone.Analytics,
    gender: 'Male',
    affiliation: Affiliation.Shared,
    age: '20-25',
    startYear: 2024,
  },
  {
    id: '62',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/62-avatar.jpg',
    name: 'Iryna Babych',
    zone: Zone.Analytics,
    gender: 'Female',
    affiliation: Affiliation.LegalAnswers,
    age: '20-25',
    startYear: 2024,
  },
  {
    id: '63',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/63-avatar.jpg',
    name: 'Illia Dermenzhy',
    zone: Zone.Analytics,
    gender: 'Male',
    affiliation: Affiliation.Shared,
    age: '20-25',
    startYear: 2025,
  },
  {
    id: '64',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/64-avatar.jpg',
    name: 'Daniil Tkachenko',
    zone: Zone.Analytics,
    gender: 'Male',
    affiliation: Affiliation.Shared,
    age: '20-25',
    startYear: 2023,
  },
  {
    id: '65',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/65-avatar.jpg',
    name: 'Bohdan Perepelytsia',
    zone: Zone.Analytics,
    gender: 'Male',
    affiliation: Affiliation.PDFAid,
    age: '20-25',
    startYear: 2024,
  },
  {
    id: '66',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/66-avatar.jpg',
    name: 'Yuliia Holovatska',
    zone: Zone.DesignAndContent,
    gender: 'Female',
    affiliation: Affiliation.BetterCV,
    age: '20-25',
    startYear: 2025,
  },
  {
    id: '67',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/67-avatar.jpg',
    name: 'Pavlo Mykytas',
    zone: Zone.Payments,
    gender: 'Male',
    affiliation: Affiliation.Shared,
    age: '25-30',
    startYear: 2022,
  },
  {
    id: '68',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/68-avatar.jpg',
    name: 'Anastasiia Mostovenko',
    zone: Zone.Product,
    gender: 'Female',
    affiliation: Affiliation.PDFAid,
    age: '20-25',
    startYear: 2024,
  },
  {
    id: '69',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/69-avatar.jpg',
    name: 'Valeriia Volkova',
    zone: Zone.DesignAndContent,
    gender: 'Female',
    affiliation: Affiliation.Tech,
    age: '20-25',
    startYear: 2025,
  },
  {
    id: '70',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/70-avatar.jpg',
    name: 'Volodymyr Bozhko',
    zone: Zone.HR,
    gender: 'Male',
    affiliation: Affiliation.Shared,
    age: '25-30',
    startYear: 2025,
  },
  {
    id: '71',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/71-avatar.jpg',
    name: 'Mykhailo Shylo',
    zone: Zone.Frontend,
    gender: 'Male',
    affiliation: Affiliation.PDFAid,
    age: '20-25',
    startYear: 2025,
  },
  {
    id: '72',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/72-avatar.jpg',
    name: 'Yuliia Zaiats',
    zone: Zone.Frontend,
    gender: 'Female',
    affiliation: Affiliation.LegalAnswers,
    age: '25-30',
    startYear: 2025,
  },
  {
    id: '73',
    avatar: 'https://kwv9prk72qe42rbz.public.blob.vercel-storage.com/73-avatar.jpg',
    name: 'Andrii Sviatovets',
    zone: Zone.Product,
    gender: 'Male',
    affiliation: Affiliation.Tech,
    age: '30+',
    startYear: 2025,
  },
];
